# **Linear Algebra & Matrix Operations in Python**
This worksheet explores the fundamental implementation of linear algebra operations using both "vanilla" Python and the NumPy library. It tracks the progression from manual algorithmic logic to optimized industry-standard practices.

**Key Contents:**

* **Manual Algorithm Logic:** Implementation of matrix multiplication using nested loops to demonstrate the underlying $O(n^3)$ mathematical process.
* **NumPy Fundamentals:** Usage of `np.array` for multi-dimensional data storage and shape manipulation.
* **Dimensionality & Transposition:** Exercises on matrix shapes, axis flipping using `.T`, and understanding row vs. column vectors.
* **Optimized Syntax:** Comparison of `np.matmul()`, `np.dot()`, and the modern `@` infix operator for performance and readability.
* **Classic Project:** A weighted scoring system project that applies vector-matrix multiplication to calculate final results from scores and weights.

In [9]:
import numpy as np

# Define a 2x3 matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Define a 3x2 matrix
B = np.array([
    [7,  8],
    [9,  10],
    [11, 12]
])

print(f"Shape of A: {A.shape}")
print(f"Shape of B: {B.shape}")

Shape of A: (2, 3)
Shape of B: (3, 2)


In [10]:
from typing import List

def matmul(A: List[List[int]], B: List[List[int]]) -> List[List[int]]:
    """
    Performs matrix multiplication A x B manually.
    """
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        raise ValueError("Incompatible dimensions: Cols of A must match Rows of B")

    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(rows_B): # or range(cols_A)
                result[i][j] += A[i][k] * B[k][j]

    return result

# Usage
print(matmul(A.tolist(), B.tolist()))

[[58, 64], [139, 154]]


In [11]:
import numpy as np

# A is (2, 3), B is (3, 2)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# 1. The Functional Approach
result_func = np.matmul(A, B)

# 2. The Infix Operator (Python 3.5+) - Cleanest and most readable
result_operator = A @ B

print(f"Result using @ operator:\n{result_operator}")
print(f"Result using np.matmul():\n{result_func}")

Result using @ operator:
[[ 58  64]
 [139 154]]
Result using np.matmul():
[[ 58  64]
 [139 154]]


In [12]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Transpose A
A_transposed = A.T

print(f"Original Shape:   {A.shape}")   # (2, 3)
print(f"Transposed Shape: {A_transposed.shape}") # (3, 2)
print("\nTransposed Matrix:")
print(A_transposed)

Original Shape:   (2, 3)
Transposed Shape: (3, 2)

Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [13]:
import numpy as np

# Define vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculation options
result_dot = np.dot(a, b)
result_at  = a @ b          # Modern Pythonic way (equivalent for 1D)

print(f"Vector A: {a}")
print(f"Vector B: {b}")
print(f"Dot Product: {result_at}")

Vector A: [1 2 3]
Vector B: [4 5 6]
Dot Product: 32


In [14]:
import numpy as np

# Column vector of weights (must sum to 1.0 for a standard average)
weights = np.array([
    [0.5],
    [0.3],
    [0.2]
])

# Row vector of individual scores
scores = np.array([[80, 70, 90]])

# Matrix multiplication (1x3) @ (3x1) = (1x1)
final_score = scores @ weights

# Squeeze or flatten to get the raw number if needed
print(f"Final Weighted Score: {final_score.item():.2f}")

Final Weighted Score: 79.00
