
# _This worksheet demonstrates **basic linear algebra** operations using NumPy:_

•**Matrix Transposition:** It defines a 2x3 matrix A and calculates its transpose.

•**Solving Linear Equations:** It defines matrices B and C, then solves the linear system BX = C for X.

•**Matrix Inverse:** It computes the inverse of matrix B.

•**Inverse Verification:** It verifies the inverse of B by multiplying B with its inverse, which should result in an identity matrix.

# **Project:** Gym Membership Revenue Model
**Objective:** Model a gym's revenue and determine the number of basic and premium memberships.

**Variables:**

**x:**   thousands of Basic members                                 
**y:** thousands of Premium members

**Revenue System:** Defined by two linear equations:

3x + 2y = 18   
2x - y = 3

**Units:** Revenue is in lakh units (scaled for simplicity).     
**Method:** Solves the system of linear equations to find the values for x and y.


In [15]:
import numpy as np
A = np.array([[1,2,3]
,[4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
B = np.array([[2,1],[1,-1]])
C = np.array([5,1])
X = np.linalg.solve(B,C)
print(X)

[2. 1.]


In [ ]:
np.linalg.inv(B)

array([[ 0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667]])

In [ ]:
inverse = np.matmul(B ,np.linalg.inv(B))
np.round(inverse)

array([[1., 0.],
       [0., 1.]])

In [14]:
# Mini Project
# Scenario: Gym Membership Revenue Model
# A gym has:
# Basic memberships (x)
# Premium memberships (y)
# Revenue system:
# 3x + 2y = 18
# 2x − y = 3
# Where:
# x = thousands of Basic members
# y = thousands of Premium members
# revenue is in lakh units (scaled for simplicity)

import numpy as np

# Coefficient matrix
A = np.array([[3, 2],
              [2, -1]])

# Revenue vector
b = np.array([18, 3])

# Solve Ax = b
solution = np.linalg.solve(A, b)

x, y = solution

print(f"Basic memberships (thousands): {x}")
print(f"Premium memberships (thousands): {y}")

print("Verification:")
print(A @ solution)

Basic memberships (thousands): 3.4285714285714284
Premium memberships (thousands): 3.8571428571428577
Verification:
[18.  3.]
