In [4]:
import numpy as np

# 1. GENERATE
# Create numbers from 1 to 50 (Note: stop value is 51 because it's exclusive)
arr = np.arange(1, 51)
print("Original Array:", arr)

# 2. RESHAPE
# Turn it into a 5x10 grid (5 rows, 10 columns)
matrix = arr.reshape(5, 10)
print("\nReshaped Matrix (5x10):\n", matrix)

# 3. FILTER & MODIFY (The Magic Step)
# Find all numbers > 30 and instantly set them to 0
# This is called "Boolean Masking"
matrix[matrix > 30] = 0

print("\nModified Matrix (Numbers > 30 are now 0):\n", matrix)

# 4. ANALYZE
# Sum up the new matrix
final_sum = np.sum(matrix)

print(f"\n✅ Final Sum: {final_sum}")


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Reshaped Matrix (5x10):
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Modified Matrix (Numbers > 30 are now 0):
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]

✅ Final Sum: 465
